#!/usr/bin/env bash
#
# clone repo to update scripts
if [[ -d /tmp/jupyter-images ]]; then
  rm -rf /tmp/jupyter-images
fi
git clone https://github.com/cellgeni/jupyter-images.git /tmp/jupyter-images

# move scripts to where they are supposed to be
if [[ -d /poststart ]]; then
  sudo rm -rf /poststart
fi
sudo mv /tmp/jupyter-images/images/base/mount-farm /usr/local/bin/mount-farm
sudo chmod +x /usr/local/bin/mount-farm
sudo mv /tmp/jupyter-images/poststart /
sudo chmod +x /poststart/*
