name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python = 3.8
  - pip
  - numpy
  - numba==0.51.2
  - cython
  - python-igraph
  - scanpy
  - python-annoy
  - cython
  - cmake
  - pandas
  - louvain 
  - leidenalg
  - scikit-learn 
  - matplotlib
  - seaborn
  - bbknn
  - h5py
  - pip: 
    - cello-classify
    - plotly
    - scvi-tools
    - scvelo
    - scirpy
    - velocyto
    - pyscenic
    - scrublet
    - scanorama
