#!/usr/bin/env bash

#Settings
DOCKERFILE_ROOT_DIR=/home/ubuntu/docker-jupyter/images
REGISTRY=quay.io/cellgeni/jupyter
LOG_DIR=$DOCKERFILE_ROOT_DIR/logs/
mkdir -p $LOG_DIR

TAG=$1
if [[ -z "$TAG" ]]; then
  # Generate a tag with epoch if not provided
  TAG=$(date +%Y%m%d)
fi

echo "🏷️ Using tag $TAG"
echo "----------------------"

echo "🐳 building base image"  | ts '[%Y-%m-%d %H:%M:%S]'
cd $DOCKERFILE_ROOT_DIR/base
docker build --build-arg tag_name=$TAG --tag "$REGISTRY:base-$TAG" . >  "$LOG_DIR/base-$TAG.build.log" | ts '[%Y-%m-%d %H:%M:%S]'

echo "🐳 🐳 🐳 building julia, r-base and python at the same time"  | ts '[%Y-%m-%d %H:%M:%S]'
cd $DOCKERFILE_ROOT_DIR/julia
docker build --build-arg tag_name=$TAG --tag "$REGISTRY:julia-$TAG" . >  "$LOG_DIR/julia-$TAG.build.log" | ts '[%Y-%m-%d %H:%M:%S]' &
julia=$!
cd $DOCKERFILE_ROOT_DIR/r-base
docker build --build-arg tag_name=$TAG --tag "$REGISTRY:r-base-$TAG" . >  "$LOG_DIR/r-base-$TAG.build.log" | ts '[%Y-%m-%d %H:%M:%S]' &
r_base=$!
cd $DOCKERFILE_ROOT_DIR/python
docker build --build-arg tag_name=$TAG --tag "$REGISTRY:python-$TAG" . >  "$LOG_DIR/python-$TAG.build.log" | ts '[%Y-%m-%d %H:%M:%S]' &
python=$!
wait $julia $r_base $python

echo "🐳 building r-full image"  | ts '[%Y-%m-%d %H:%M:%S]'
cd $DOCKERFILE_ROOT_DIR/r-full
docker build --build-arg tag_name=$TAG --tag "$REGISTRY:r-full-$TAG"  . >  "$LOG_DIR/r-full-$TAG.build.log" | ts '[%Y-%m-%d %H:%M:%S]'

echo "🐳 🐳 building python-r-full and teichlabn at the same time"  | ts '[%Y-%m-%d %H:%M:%S]'
cd $DOCKERFILE_ROOT_DIR/python
docker build --build-arg tag_name=$TAG --build-arg parent_image="r-full" --build-arg image_name="python-r-full" --tag "$REGISTRY:python-r-full-$TAG" . >  "$LOG_DIR/python-r-full-$TAG.build.log" | ts '[%Y-%m-%d %H:%M:%S]' &
python_r_full=$!
cd $DOCKERFILE_ROOT_DIR/teichlab
docker build --build-arg tag_name=$TAG --tag "$REGISTRY:teichlab-$TAG" . >  "$LOG_DIR/teichlab-$TAG.build.log" | ts '[%Y-%m-%d %H:%M:%S]' &
teichlab=$!
wait $python_r_full $teichlab

echo "finished building"  | ts '[%Y-%m-%d %H:%M:%S]'
#./push_all $TAG
