#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "No tag argument supplied."
  echo " ./get_info <TAG>"
  exit
fi

DOCKERFILE_ROOT_DIR=/home/ubuntu/docker-jupyter/images
REGISTRY=quay.io/prete/docker-jupyter
TAG=$1

mkdir -p "$DOCKERFILE_ROOT_DIR/logs/"

for IMAGE in $(cat $DOCKERFILE_ROOT_DIR/build_list.txt)
do
    mkdir -p "$DOCKERFILE_ROOT_DIR/logs/$IMAGE"
    docker run --rm -it -v $DOCKERFILE_ROOT_DIR/logs/$IMAGE:/out "$REGISTRY:$IMAGE-$TAG" bash -c "cp /sanger/* /out" 
done

