#!/usr/bin/env bash

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -t|--tag) TAG=$2 ; shift ;;
        -r|--registry) REGISTRY=$2 ; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done


if [[ -z "$TAG" ]]; then
  echo "No tag argument supplied."
  echo " ./push_all --tag <TAG>"
  exit
fi

if [[ -z "$REGISTRY" ]]; then
   REGISTRY=quay.io/cellgeni/jupyter
   echo "No registry supplied. Using default: $REGISTRY"
fi

for IMAGE in $(cat build_list.txt)
do
    echo "Pushing 📡  $REGISTRY:$IMAGE-$TAG" 
    docker push "$REGISTRY:$IMAGE-$TAG"
done

