name: teichlab
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python = 3.8
  - pip >= 20.2.4
  - numpy
  - cython
  - python-igraph
  - plotly
  - pytest
  - samtools
  - bcftools
  - pandas
  - louvain
  - leidenalg
  - gpy  
  - scanpy 
  - scikit-learn 
  - matplotlib 
  - snakemake 
  - cmake 
  - sccaf 
  - pytest 
  - plotly 
#  - ggplot
  - scvi-tools 
  - bbknn 
  - h5py
  - scvelo
  - pip:
    - velocyto
#    - fitsne
    - spatialde
    - wot 
#    - polo     
    - cellphonedb
    - pyscenic
    - scirpy
    - palantir

